const tempData = [
  {
    name: "Afghanistan",
    capital: "Kabul",
    region: "Asia",
    population: 40218234,
    flag: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg",
    independent: false,
  },
  {
    name: "Åland Islands",
    capital: "Mariehamn",
    region: "Europe",
    population: 28875,
    flag: "https://flagcdn.com/ax.svg",
    independent: false,
  },
  {
    name: "Albania",
    capital: "Tirana",
    region: "Europe",
    population: 2837743,
    flag: "https://flagcdn.com/al.svg",
    independent: false,
  },
  {
    name: "Algeria",
    capital: "Algiers",
    region: "Africa",
    population: 44700000,
    flag: "https://flagcdn.com/dz.svg",
    independent: false,
  },
  {
    name: "American Samoa",
    capital: "Pago Pago",
    region: "Oceania",
    population: 55197,
    flag: "https://flagcdn.com/as.svg",
    independent: false,
  },
  {
    name: "Andorra",
    capital: "Andorra la Vella",
    region: "Europe",
    population: 77265,
    flag: "https://flagcdn.com/ad.svg",
    independent: false,
  },
  {
    name: "Angola",
    capital: "Luanda",
    region: "Africa",
    population: 32866268,
    flag: "https://flagcdn.com/ao.svg",
    independent: false,
  },
  {
    name: "Anguilla",
    capital: "The Valley",
    region: "Americas",
    population: 13452,
    flag: "https://flagcdn.com/ai.svg",
    independent: false,
  },
  {
    name: "Antarctica",
    region: "Polar",
    population: 1000,
    flag: "https://flagcdn.com/aq.svg",
    independent: false,
  },
  {
    name: "Antigua and Barbuda",
    capital: "Saint John's",
    region: "Americas",
    population: 97928,
    flag: "https://flagcdn.com/ag.svg",
    independent: false,
  },
  {
    name: "Argentina",
    capital: "Buenos Aires",
    region: "Americas",
    population: 45376763,
    flag: "https://flagcdn.com/ar.svg",
    independent: false,
  },
  {
    name: "Armenia",
    capital: "Yerevan",
    region: "Asia",
    population: 2963234,
    flag: "https://flagcdn.com/am.svg",
    independent: false,
  },
  {
    name: "Aruba",
    capital: "Oranjestad",
    region: "Americas",
    population: 106766,
    flag: "https://flagcdn.com/aw.svg",
    independent: false,
  },
  {
    name: "Australia",
    capital: "Canberra",
    region: "Oceania",
    population: 25687041,
    flag: "https://flagcdn.com/au.svg",
    independent: false,
  },
  {
    name: "Austria",
    capital: "Vienna",
    region: "Europe",
    population: 8917205,
    flag: "https://flagcdn.com/at.svg",
    independent: false,
  },
  {
    name: "Azerbaijan",
    capital: "Baku",
    region: "Asia",
    population: 10110116,
    flag: "https://flagcdn.com/az.svg",
    independent: false,
  },
  {
    name: "Bahamas",
    capital: "Nassau",
    region: "Americas",
    population: 393248,
    flag: "https://flagcdn.com/bs.svg",
    independent: false,
  },
  {
    name: "Bahrain",
    capital: "Manama",
    region: "Asia",
    population: 1701583,
    flag: "https://flagcdn.com/bh.svg",
    independent: false,
  },
  {
    name: "Bangladesh",
    capital: "Dhaka",
    region: "Asia",
    population: 164689383,
    flag: "https://flagcdn.com/bd.svg",
    independent: false,
  },
  {
    name: "Barbados",
    capital: "Bridgetown",
    region: "Americas",
    population: 287371,
    flag: "https://flagcdn.com/bb.svg",
    independent: false,
  },
  {
    name: "Belarus",
    capital: "Minsk",
    region: "Europe",
    population: 9398861,
    flag: "https://flagcdn.com/by.svg",
    independent: false,
  },
  {
    name: "Belgium",
    capital: "Brussels",
    region: "Europe",
    population: 11555997,
    flag: "https://flagcdn.com/be.svg",
    independent: false,
  },
  {
    name: "Belize",
    capital: "Belmopan",
    region: "Americas",
    population: 397621,
    flag: "https://flagcdn.com/bz.svg",
    independent: false,
  },
  {
    name: "Benin",
    capital: "Porto-Novo",
    region: "Africa",
    population: 12123198,
    flag: "https://flagcdn.com/bj.svg",
    independent: false,
  },
  {
    name: "Bermuda",
    capital: "Hamilton",
    region: "Americas",
    population: 63903,
    flag: "https://flagcdn.com/bm.svg",
    independent: false,
  },
  {
    name: "Bhutan",
    capital: "Thimphu",
    region: "Asia",
    population: 771612,
    flag: "https://flagcdn.com/bt.svg",
    independent: false,
  },
  {
    name: "Bolivia (Plurinational State of)",
    capital: "Sucre",
    region: "Americas",
    population: 11673029,
    flag: "https://flagcdn.com/bo.svg",
    independent: false,
  },
  {
    name: "Bonaire, Sint Eustatius and Saba",
    capital: "Kralendijk",
    region: "Americas",
    population: 17408,
    flag: "https://flagcdn.com/bq.svg",
    independent: false,
  },
  {
    name: "Bosnia and Herzegovina",
    capital: "Sarajevo",
    region: "Europe",
    population: 3280815,
    flag: "https://flagcdn.com/ba.svg",
    independent: false,
  },
  {
    name: "Botswana",
    capital: "Gaborone",
    region: "Africa",
    population: 2351625,
    flag: "https://flagcdn.com/bw.svg",
    independent: false,
  },
  {
    name: "Bouvet Island",
    region: "Antarctic Ocean",
    population: 0,
    flag: "https://flagcdn.com/bv.svg",
    independent: false,
  },
  {
    name: "Brazil",
    capital: "Brasília",
    region: "Americas",
    population: 212559409,
    flag: "https://flagcdn.com/br.svg",
    independent: false,
  },
  {
    name: "British Indian Ocean Territory",
    capital: "Diego Garcia",
    region: "Africa",
    population: 3000,
    flag: "https://flagcdn.com/io.svg",
    independent: false,
  },
  {
    name: "United States Minor Outlying Islands",
    region: "Americas",
    population: 300,
    flag: "https://flagcdn.com/um.svg",
    independent: false,
  },
  {
    name: "Virgin Islands (British)",
    capital: "Road Town",
    region: "Americas",
    population: 30237,
    flag: "https://flagcdn.com/vg.svg",
    independent: false,
  },
  {
    name: "Virgin Islands (U.S.)",
    capital: "Charlotte Amalie",
    region: "Americas",
    population: 106290,
    flag: "https://flagcdn.com/vi.svg",
    independent: false,
  },
  {
    name: "Brunei Darussalam",
    capital: "Bandar Seri Begawan",
    region: "Asia",
    population: 437483,
    flag: "https://flagcdn.com/bn.svg",
    independent: false,
  },
  {
    name: "Bulgaria",
    capital: "Sofia",
    region: "Europe",
    population: 6927288,
    flag: "https://flagcdn.com/bg.svg",
    independent: false,
  },
  {
    name: "Burkina Faso",
    capital: "Ouagadougou",
    region: "Africa",
    population: 20903278,
    flag: "https://flagcdn.com/bf.svg",
    independent: false,
  },
  {
    name: "Burundi",
    capital: "Gitega",
    region: "Africa",
    population: 11890781,
    flag: "https://flagcdn.com/bi.svg",
    independent: false,
  },
  {
    name: "Cambodia",
    capital: "Phnom Penh",
    region: "Asia",
    population: 16718971,
    flag: "https://flagcdn.com/kh.svg",
    independent: false,
  },
  {
    name: "Cameroon",
    capital: "Yaoundé",
    region: "Africa",
    population: 26545864,
    flag: "https://flagcdn.com/cm.svg",
    independent: false,
  },
  {
    name: "Canada",
    capital: "Ottawa",
    region: "Americas",
    population: 38005238,
    flag: "https://flagcdn.com/ca.svg",
    independent: false,
  },
  {
    name: "Cabo Verde",
    capital: "Praia",
    region: "Africa",
    population: 555988,
    flag: "https://flagcdn.com/cv.svg",
    independent: false,
  },
  {
    name: "Cayman Islands",
    capital: "George Town",
    region: "Americas",
    population: 65720,
    flag: "https://flagcdn.com/ky.svg",
    independent: false,
  },
  {
    name: "Central African Republic",
    capital: "Bangui",
    region: "Africa",
    population: 4829764,
    flag: "https://flagcdn.com/cf.svg",
    independent: false,
  },
  {
    name: "Chad",
    capital: "N'Djamena",
    region: "Africa",
    population: 16425859,
    flag: "https://flagcdn.com/td.svg",
    independent: false,
  },
  {
    name: "Chile",
    capital: "Santiago",
    region: "Americas",
    population: 19116209,
    flag: "https://flagcdn.com/cl.svg",
    independent: false,
  },
  {
    name: "China",
    capital: "Beijing",
    region: "Asia",
    population: 1402112000,
    flag: "https://flagcdn.com/cn.svg",
    independent: false,
  },
  {
    name: "Christmas Island",
    capital: "Flying Fish Cove",
    region: "Oceania",
    population: 2072,
    flag: "https://flagcdn.com/cx.svg",
    independent: false,
  },
  {
    name: "Cocos (Keeling) Islands",
    capital: "West Island",
    region: "Oceania",
    population: 550,
    flag: "https://flagcdn.com/cc.svg",
    independent: false,
  },
  {
    name: "Colombia",
    capital: "Bogotá",
    region: "Americas",
    population: 50882884,
    flag: "https://flagcdn.com/co.svg",
    independent: false,
  },
  {
    name: "Comoros",
    capital: "Moroni",
    region: "Africa",
    population: 869595,
    flag: "https://flagcdn.com/km.svg",
    independent: false,
  },
  {
    name: "Congo",
    capital: "Brazzaville",
    region: "Africa",
    population: 5518092,
    flag: "https://flagcdn.com/cg.svg",
    independent: false,
  },
  {
    name: "Congo (Democratic Republic of the)",
    capital: "Kinshasa",
    region: "Africa",
    population: 89561404,
    flag: "https://flagcdn.com/cd.svg",
    independent: false,
  },
  {
    name: "Cook Islands",
    capital: "Avarua",
    region: "Oceania",
    population: 18100,
    flag: "https://flagcdn.com/ck.svg",
    independent: false,
  },
  {
    name: "Costa Rica",
    capital: "San José",
    region: "Americas",
    population: 5094114,
    flag: "https://flagcdn.com/cr.svg",
    independent: false,
  },
  {
    name: "Croatia",
    capital: "Zagreb",
    region: "Europe",
    population: 4047200,
    flag: "https://flagcdn.com/hr.svg",
    independent: false,
  },
  {
    name: "Cuba",
    capital: "Havana",
    region: "Americas",
    population: 11326616,
    flag: "https://flagcdn.com/cu.svg",
    independent: false,
  },
  {
    name: "Curaçao",
    capital: "Willemstad",
    region: "Americas",
    population: 155014,
    flag: "https://flagcdn.com/cw.svg",
    independent: false,
  },
  {
    name: "Cyprus",
    capital: "Nicosia",
    region: "Europe",
    population: 1207361,
    flag: "https://flagcdn.com/cy.svg",
    independent: false,
  },
  {
    name: "Czech Republic",
    capital: "Prague",
    region: "Europe",
    population: 10698896,
    flag: "https://flagcdn.com/cz.svg",
    independent: false,
  },
  {
    name: "Denmark",
    capital: "Copenhagen",
    region: "Europe",
    population: 5831404,
    flag: "https://flagcdn.com/dk.svg",
    independent: false,
  },
  {
    name: "Djibouti",
    capital: "Djibouti",
    region: "Africa",
    population: 988002,
    flag: "https://flagcdn.com/dj.svg",
    independent: false,
  },
  {
    name: "Dominica",
    capital: "Roseau",
    region: "Americas",
    population: 71991,
    flag: "https://flagcdn.com/dm.svg",
    independent: false,
  },
  {
    name: "Dominican Republic",
    capital: "Santo Domingo",
    region: "Americas",
    population: 10847904,
    flag: "https://flagcdn.com/do.svg",
    independent: false,
  },
  {
    name: "Ecuador",
    capital: "Quito",
    region: "Americas",
    population: 17643060,
    flag: "https://flagcdn.com/ec.svg",
    independent: false,
  },
  {
    name: "Egypt",
    capital: "Cairo",
    region: "Africa",
    population: 102334403,
    flag: "https://flagcdn.com/eg.svg",
    independent: false,
  },
  {
    name: "El Salvador",
    capital: "San Salvador",
    region: "Americas",
    population: 6486201,
    flag: "https://flagcdn.com/sv.svg",
    independent: false,
  },
  {
    name: "Equatorial Guinea",
    capital: "Malabo",
    region: "Africa",
    population: 1402985,
    flag: "https://flagcdn.com/gq.svg",
    independent: false,
  },
  {
    name: "Eritrea",
    capital: "Asmara",
    region: "Africa",
    population: 5352000,
    flag: "https://flagcdn.com/er.svg",
    independent: false,
  },
  {
    name: "Estonia",
    capital: "Tallinn",
    region: "Europe",
    population: 1331057,
    flag: "https://flagcdn.com/ee.svg",
    independent: false,
  },
  {
    name: "Ethiopia",
    capital: "Addis Ababa",
    region: "Africa",
    population: 114963583,
    flag: "https://flagcdn.com/et.svg",
    independent: false,
  },
  {
    name: "Falkland Islands (Malvinas)",
    capital: "Stanley",
    region: "Americas",
    population: 2563,
    flag: "https://flagcdn.com/fk.svg",
    independent: false,
  },
  {
    name: "Faroe Islands",
    capital: "Tórshavn",
    region: "Europe",
    population: 48865,
    flag: "https://flagcdn.com/fo.svg",
    independent: false,
  },
  {
    name: "Fiji",
    capital: "Suva",
    region: "Oceania",
    population: 896444,
    flag: "https://flagcdn.com/fj.svg",
    independent: false,
  },
  {
    name: "Finland",
    capital: "Helsinki",
    region: "Europe",
    population: 5530719,
    flag: "https://flagcdn.com/fi.svg",
    independent: false,
  },
  {
    name: "France",
    capital: "Paris",
    region: "Europe",
    population: 67391582,
    flag: "https://flagcdn.com/fr.svg",
    independent: false,
  },
  {
    name: "French Guiana",
    capital: "Cayenne",
    region: "Americas",
    population: 254541,
    flag: "https://flagcdn.com/gf.svg",
    independent: false,
  },
  {
    name: "French Polynesia",
    capital: "Papeetē",
    region: "Oceania",
    population: 280904,
    flag: "https://flagcdn.com/pf.svg",
    independent: false,
  },
  {
    name: "French Southern Territories",
    capital: "Port-aux-Français",
    region: "Africa",
    population: 140,
    flag: "https://flagcdn.com/tf.svg",
    independent: false,
  },
  {
    name: "Gabon",
    capital: "Libreville",
    region: "Africa",
    population: 2225728,
    flag: "https://flagcdn.com/ga.svg",
    independent: false,
  },
  {
    name: "Gambia",
    capital: "Banjul",
    region: "Africa",
    population: 2416664,
    flag: "https://flagcdn.com/gm.svg",
    independent: false,
  },
  {
    name: "Georgia",
    capital: "Tbilisi",
    region: "Asia",
    population: 3714000,
    flag: "https://flagcdn.com/ge.svg",
    independent: false,
  },
  {
    name: "Germany",
    capital: "Berlin",
    region: "Europe",
    population: 83240525,
    flag: "https://flagcdn.com/de.svg",
    independent: false,
  },
  {
    name: "Ghana",
    capital: "Accra",
    region: "Africa",
    population: 31072945,
    flag: "https://flagcdn.com/gh.svg",
    independent: false,
  },
  {
    name: "Gibraltar",
    capital: "Gibraltar",
    region: "Europe",
    population: 33691,
    flag: "https://flagcdn.com/gi.svg",
    independent: false,
  },
  {
    name: "Greece",
    capital: "Athens",
    region: "Europe",
    population: 10715549,
    flag: "https://flagcdn.com/gr.svg",
    independent: false,
  },
  {
    name: "Greenland",
    capital: "Nuuk",
    region: "Americas",
    population: 56367,
    flag: "https://flagcdn.com/gl.svg",
    independent: false,
  },
  {
    name: "Grenada",
    capital: "St. George's",
    region: "Americas",
    population: 112519,
    flag: "https://flagcdn.com/gd.svg",
    independent: false,
  },
  {
    name: "Guadeloupe",
    capital: "Basse-Terre",
    region: "Americas",
    population: 400132,
    flag: "https://flagcdn.com/gp.svg",
    independent: false,
  },
  {
    name: "Guam",
    capital: "Hagåtña",
    region: "Oceania",
    population: 168783,
    flag: "https://flagcdn.com/gu.svg",
    independent: false,
  },
  {
    name: "Guatemala",
    capital: "Guatemala City",
    region: "Americas",
    population: 16858333,
    flag: "https://flagcdn.com/gt.svg",
    independent: false,
  },
  {
    name: "Guernsey",
    capital: "St. Peter Port",
    region: "Europe",
    population: 62999,
    flag: "https://flagcdn.com/gg.svg",
    independent: false,
  },
  {
    name: "Guinea",
    capital: "Conakry",
    region: "Africa",
    population: 13132792,
    flag: "https://flagcdn.com/gn.svg",
    independent: false,
  },
  {
    name: "Guinea-Bissau",
    capital: "Bissau",
    region: "Africa",
    population: 1967998,
    flag: "https://flagcdn.com/gw.svg",
    independent: false,
  },
  {
    name: "Guyana",
    capital: "Georgetown",
    region: "Americas",
    population: 786559,
    flag: "https://flagcdn.com/gy.svg",
    independent: false,
  },
  {
    name: "Haiti",
    capital: "Port-au-Prince",
    region: "Americas",
    population: 11402533,
    flag: "https://flagcdn.com/ht.svg",
    independent: false,
  },
  {
    name: "Heard Island and McDonald Islands",
    region: "Antarctic",
    population: 0,
    flag: "https://flagcdn.com/hm.svg",
    independent: false,
  },
  {
    name: "Vatican City",
    capital: "Vatican City",
    region: "Europe",
    population: 451,
    flag: "https://flagcdn.com/va.svg",
    independent: false,
  },
  {
    name: "Honduras",
    capital: "Tegucigalpa",
    region: "Americas",
    population: 9904608,
    flag: "https://flagcdn.com/hn.svg",
    independent: false,
  },
  {
    name: "Hungary",
    capital: "Budapest",
    region: "Europe",
    population: 9749763,
    flag: "https://flagcdn.com/hu.svg",
    independent: false,
  },
  {
    name: "Hong Kong",
    capital: "City of Victoria",
    region: "Asia",
    population: 7481800,
    flag: "https://flagcdn.com/hk.svg",
    independent: false,
  },
  {
    name: "Iceland",
    capital: "Reykjavík",
    region: "Europe",
    population: 366425,
    flag: "https://flagcdn.com/is.svg",
    independent: false,
  },
  {
    name: "India",
    capital: "New Delhi",
    region: "Asia",
    population: 1380004385,
    flag: "https://flagcdn.com/in.svg",
    independent: false,
  },
  {
    name: "Indonesia",
    capital: "Jakarta",
    region: "Asia",
    population: 273523621,
    flag: "https://flagcdn.com/id.svg",
    independent: false,
  },
  {
    name: "Ivory Coast",
    capital: "Yamoussoukro",
    region: "Africa",
    population: 26378275,
    flag: "https://flagcdn.com/ci.svg",
    independent: false,
  },
  {
    name: "Iran (Islamic Republic of)",
    capital: "Tehran",
    region: "Asia",
    population: 83992953,
    flag: "https://flagcdn.com/ir.svg",
    independent: false,
  },
  {
    name: "Iraq",
    capital: "Baghdad",
    region: "Asia",
    population: 40222503,
    flag: "https://flagcdn.com/iq.svg",
    independent: false,
  },
  {
    name: "Ireland",
    capital: "Dublin",
    region: "Europe",
    population: 4994724,
    flag: "https://flagcdn.com/ie.svg",
    independent: false,
  },
  {
    name: "Isle of Man",
    capital: "Douglas",
    region: "Europe",
    population: 85032,
    flag: "https://flagcdn.com/im.svg",
    independent: false,
  },
  {
    name: "Israel",
    capital: "Jerusalem",
    region: "Asia",
    population: 9216900,
    flag: "https://flagcdn.com/il.svg",
    independent: false,
  },
  {
    name: "Italy",
    capital: "Rome",
    region: "Europe",
    population: 59554023,
    flag: "https://flagcdn.com/it.svg",
    independent: false,
  },
  {
    name: "Jamaica",
    capital: "Kingston",
    region: "Americas",
    population: 2961161,
    flag: "https://flagcdn.com/jm.svg",
    independent: false,
  },
  {
    name: "Japan",
    capital: "Tokyo",
    region: "Asia",
    population: 125836021,
    flag: "https://flagcdn.com/jp.svg",
    independent: false,
  },
  {
    name: "Jersey",
    capital: "Saint Helier",
    region: "Europe",
    population: 100800,
    flag: "https://flagcdn.com/je.svg",
    independent: false,
  },
  {
    name: "Jordan",
    capital: "Amman",
    region: "Asia",
    population: 10203140,
    flag: "https://flagcdn.com/jo.svg",
    independent: false,
  },
  {
    name: "Kazakhstan",
    capital: "Nur-Sultan",
    region: "Asia",
    population: 18754440,
    flag: "https://flagcdn.com/kz.svg",
    independent: false,
  },
  {
    name: "Kenya",
    capital: "Nairobi",
    region: "Africa",
    population: 53771300,
    flag: "https://flagcdn.com/ke.svg",
    independent: false,
  },
  {
    name: "Kiribati",
    capital: "South Tarawa",
    region: "Oceania",
    population: 119446,
    flag: "https://flagcdn.com/ki.svg",
    independent: false,
  },
  {
    name: "Kuwait",
    capital: "Kuwait City",
    region: "Asia",
    population: 4270563,
    flag: "https://flagcdn.com/kw.svg",
    independent: false,
  },
  {
    name: "Kyrgyzstan",
    capital: "Bishkek",
    region: "Asia",
    population: 6591600,
    flag: "https://flagcdn.com/kg.svg",
    independent: false,
  },
  {
    name: "Lao People's Democratic Republic",
    capital: "Vientiane",
    region: "Asia",
    population: 7275556,
    flag: "https://flagcdn.com/la.svg",
    independent: false,
  },
  {
    name: "Latvia",
    capital: "Riga",
    region: "Europe",
    population: 1901548,
    flag: "https://flagcdn.com/lv.svg",
    independent: false,
  },
  {
    name: "Lebanon",
    capital: "Beirut",
    region: "Asia",
    population: 6825442,
    flag: "https://flagcdn.com/lb.svg",
    independent: false,
  },
  {
    name: "Lesotho",
    capital: "Maseru",
    region: "Africa",
    population: 2142252,
    flag: "https://flagcdn.com/ls.svg",
    independent: false,
  },
  {
    name: "Liberia",
    capital: "Monrovia",
    region: "Africa",
    population: 5057677,
    flag: "https://flagcdn.com/lr.svg",
    independent: false,
  },
  {
    name: "Libya",
    capital: "Tripoli",
    region: "Africa",
    population: 6871287,
    flag: "https://flagcdn.com/ly.svg",
    independent: false,
  },
  {
    name: "Liechtenstein",
    capital: "Vaduz",
    region: "Europe",
    population: 38137,
    flag: "https://flagcdn.com/li.svg",
    independent: false,
  },
  {
    name: "Lithuania",
    capital: "Vilnius",
    region: "Europe",
    population: 2794700,
    flag: "https://flagcdn.com/lt.svg",
    independent: false,
  },
  {
    name: "Luxembourg",
    capital: "Luxembourg",
    region: "Europe",
    population: 632275,
    flag: "https://flagcdn.com/lu.svg",
    independent: false,
  },
  {
    name: "Macao",
    region: "Asia",
    population: 649342,
    flag: "https://flagcdn.com/mo.svg",
    independent: false,
  },
  {
    name: "North Macedonia",
    capital: "Skopje",
    region: "Europe",
    population: 2083380,
    flag: "https://flagcdn.com/mk.svg",
    independent: false,
  },
  {
    name: "Madagascar",
    capital: "Antananarivo",
    region: "Africa",
    population: 27691019,
    flag: "https://flagcdn.com/mg.svg",
    independent: false,
  },
  {
    name: "Malawi",
    capital: "Lilongwe",
    region: "Africa",
    population: 19129955,
    flag: "https://flagcdn.com/mw.svg",
    independent: false,
  },
  {
    name: "Malaysia",
    capital: "Kuala Lumpur",
    region: "Asia",
    population: 32365998,
    flag: "https://flagcdn.com/my.svg",
    independent: false,
  },
  {
    name: "Maldives",
    capital: "Malé",
    region: "Asia",
    population: 540542,
    flag: "https://flagcdn.com/mv.svg",
    independent: false,
  },
  {
    name: "Mali",
    capital: "Bamako",
    region: "Africa",
    population: 20250834,
    flag: "https://flagcdn.com/ml.svg",
    independent: false,
  },
  {
    name: "Malta",
    capital: "Valletta",
    region: "Europe",
    population: 525285,
    flag: "https://flagcdn.com/mt.svg",
    independent: false,
  },
  {
    name: "Marshall Islands",
    capital: "Majuro",
    region: "Oceania",
    population: 59194,
    flag: "https://flagcdn.com/mh.svg",
    independent: false,
  },
  {
    name: "Martinique",
    capital: "Fort-de-France",
    region: "Americas",
    population: 378243,
    flag: "https://flagcdn.com/mq.svg",
    independent: false,
  },
  {
    name: "Mauritania",
    capital: "Nouakchott",
    region: "Africa",
    population: 4649660,
    flag: "https://flagcdn.com/mr.svg",
    independent: false,
  },
  {
    name: "Mauritius",
    capital: "Port Louis",
    region: "Africa",
    population: 1265740,
    flag: "https://flagcdn.com/mu.svg",
    independent: false,
  },
  {
    name: "Mayotte",
    capital: "Mamoudzou",
    region: "Africa",
    population: 226915,
    flag: "https://flagcdn.com/yt.svg",
    independent: false,
  },
  {
    name: "Mexico",
    capital: "Mexico City",
    region: "Americas",
    population: 128932753,
    flag: "https://flagcdn.com/mx.svg",
    independent: false,
  },
  {
    name: "Micronesia (Federated States of)",
    capital: "Palikir",
    region: "Oceania",
    population: 115021,
    flag: "https://flagcdn.com/fm.svg",
    independent: false,
  },
  {
    name: "Moldova (Republic of)",
    capital: "Chișinău",
    region: "Europe",
    population: 2617820,
    flag: "https://flagcdn.com/md.svg",
    independent: false,
  },
  {
    name: "Monaco",
    capital: "Monaco",
    region: "Europe",
    population: 39244,
    flag: "https://flagcdn.com/mc.svg",
    independent: false,
  },
  {
    name: "Mongolia",
    capital: "Ulan Bator",
    region: "Asia",
    population: 3278292,
    flag: "https://flagcdn.com/mn.svg",
    independent: false,
  },
  {
    name: "Montenegro",
    capital: "Podgorica",
    region: "Europe",
    population: 621718,
    flag: "https://flagcdn.com/me.svg",
    independent: false,
  },
  {
    name: "Montserrat",
    capital: "Plymouth",
    region: "Americas",
    population: 4922,
    flag: "https://flagcdn.com/ms.svg",
    independent: false,
  },
  {
    name: "Morocco",
    capital: "Rabat",
    region: "Africa",
    population: 36910558,
    flag: "https://flagcdn.com/ma.svg",
    independent: false,
  },
  {
    name: "Mozambique",
    capital: "Maputo",
    region: "Africa",
    population: 31255435,
    flag: "https://flagcdn.com/mz.svg",
    independent: false,
  },
  {
    name: "Myanmar",
    capital: "Naypyidaw",
    region: "Asia",
    population: 54409794,
    flag: "https://flagcdn.com/mm.svg",
    independent: false,
  },
  {
    name: "Namibia",
    capital: "Windhoek",
    region: "Africa",
    population: 2540916,
    flag: "https://flagcdn.com/na.svg",
    independent: false,
  },
  {
    name: "Nauru",
    capital: "Yaren",
    region: "Oceania",
    population: 10834,
    flag: "https://flagcdn.com/nr.svg",
    independent: false,
  },
  {
    name: "Nepal",
    capital: "Kathmandu",
    region: "Asia",
    population: 29136808,
    flag: "https://flagcdn.com/np.svg",
    independent: false,
  },
  {
    name: "Netherlands",
    capital: "Amsterdam",
    region: "Europe",
    population: 17441139,
    flag: "https://flagcdn.com/nl.svg",
    independent: false,
  },
  {
    name: "New Caledonia",
    capital: "Nouméa",
    region: "Oceania",
    population: 271960,
    flag: "https://flagcdn.com/nc.svg",
    independent: false,
  },
  {
    name: "New Zealand",
    capital: "Wellington",
    region: "Oceania",
    population: 5084300,
    flag: "https://flagcdn.com/nz.svg",
    independent: false,
  },
  {
    name: "Nicaragua",
    capital: "Managua",
    region: "Americas",
    population: 6624554,
    flag: "https://flagcdn.com/ni.svg",
    independent: false,
  },
  {
    name: "Niger",
    capital: "Niamey",
    region: "Africa",
    population: 24206636,
    flag: "https://flagcdn.com/ne.svg",
    independent: false,
  },
  {
    name: "Nigeria",
    capital: "Abuja",
    region: "Africa",
    population: 206139587,
    flag: "https://flagcdn.com/ng.svg",
    independent: false,
  },
  {
    name: "Niue",
    capital: "Alofi",
    region: "Oceania",
    population: 1470,
    flag: "https://flagcdn.com/nu.svg",
    independent: false,
  },
  {
    name: "Norfolk Island",
    capital: "Kingston",
    region: "Oceania",
    population: 2302,
    flag: "https://flagcdn.com/nf.svg",
    independent: false,
  },
  {
    name: "Korea (Democratic People's Republic of)",
    capital: "Pyongyang",
    region: "Asia",
    population: 25778815,
    flag: "https://flagcdn.com/kp.svg",
    independent: false,
  },
  {
    name: "Northern Mariana Islands",
    capital: "Saipan",
    region: "Oceania",
    population: 57557,
    flag: "https://flagcdn.com/mp.svg",
    independent: false,
  },
  {
    name: "Norway",
    capital: "Oslo",
    region: "Europe",
    population: 5379475,
    flag: "https://flagcdn.com/no.svg",
    independent: false,
  },
  {
    name: "Oman",
    capital: "Muscat",
    region: "Asia",
    population: 5106622,
    flag: "https://flagcdn.com/om.svg",
    independent: false,
  },
  {
    name: "Pakistan",
    capital: "Islamabad",
    region: "Asia",
    population: 220892331,
    flag: "https://flagcdn.com/pk.svg",
    independent: false,
  },
  {
    name: "Palau",
    capital: "Ngerulmud",
    region: "Oceania",
    population: 18092,
    flag: "https://flagcdn.com/pw.svg",
    independent: false,
  },
  {
    name: "Palestine, State of",
    capital: "Ramallah",
    region: "Asia",
    population: 4803269,
    flag: "https://flagcdn.com/ps.svg",
    independent: false,
  },
  {
    name: "Panama",
    capital: "Panama City",
    region: "Americas",
    population: 4314768,
    flag: "https://flagcdn.com/pa.svg",
    independent: false,
  },
  {
    name: "Papua New Guinea",
    capital: "Port Moresby",
    region: "Oceania",
    population: 8947027,
    flag: "https://flagcdn.com/pg.svg",
    independent: false,
  },
  {
    name: "Paraguay",
    capital: "Asunción",
    region: "Americas",
    population: 7132530,
    flag: "https://flagcdn.com/py.svg",
    independent: false,
  },
  {
    name: "Peru",
    capital: "Lima",
    region: "Americas",
    population: 32971846,
    flag: "https://flagcdn.com/pe.svg",
    independent: false,
  },
  {
    name: "Philippines",
    capital: "Manila",
    region: "Asia",
    population: 109581085,
    flag: "https://flagcdn.com/ph.svg",
    independent: false,
  },
  {
    name: "Pitcairn",
    capital: "Adamstown",
    region: "Oceania",
    population: 56,
    flag: "https://flagcdn.com/pn.svg",
    independent: false,
  },
  {
    name: "Poland",
    capital: "Warsaw",
    region: "Europe",
    population: 37950802,
    flag: "https://flagcdn.com/pl.svg",
    independent: false,
  },
  {
    name: "Portugal",
    capital: "Lisbon",
    region: "Europe",
    population: 10305564,
    flag: "https://flagcdn.com/pt.svg",
    independent: false,
  },
  {
    name: "Puerto Rico",
    capital: "San Juan",
    region: "Americas",
    population: 3194034,
    flag: "https://flagcdn.com/pr.svg",
    independent: false,
  },
  {
    name: "Qatar",
    capital: "Doha",
    region: "Asia",
    population: 2881060,
    flag: "https://flagcdn.com/qa.svg",
    independent: false,
  },
  {
    name: "Republic of Kosovo",
    capital: "Pristina",
    region: "Europe",
    population: 1775378,
    flag: "https://flagcdn.com/xk.svg",
    independent: false,
  },
  {
    name: "Réunion",
    capital: "Saint-Denis",
    region: "Africa",
    population: 840974,
    flag: "https://flagcdn.com/re.svg",
    independent: false,
  },
  {
    name: "Romania",
    capital: "Bucharest",
    region: "Europe",
    population: 19286123,
    flag: "https://flagcdn.com/ro.svg",
    independent: false,
  },
  {
    name: "Russian Federation",
    capital: "Moscow",
    region: "Europe",
    population: 144104080,
    flag: "https://flagcdn.com/ru.svg",
    independent: false,
  },
  {
    name: "Rwanda",
    capital: "Kigali",
    region: "Africa",
    population: 12952209,
    flag: "https://flagcdn.com/rw.svg",
    independent: false,
  },
  {
    name: "Saint Barthélemy",
    capital: "Gustavia",
    region: "Americas",
    population: 9417,
    flag: "https://flagcdn.com/bl.svg",
    independent: false,
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    capital: "Jamestown",
    region: "Africa",
    population: 4255,
    flag: "https://flagcdn.com/sh.svg",
    independent: false,
  },
  {
    name: "Saint Kitts and Nevis",
    capital: "Basseterre",
    region: "Americas",
    population: 53192,
    flag: "https://flagcdn.com/kn.svg",
    independent: false,
  },
  {
    name: "Saint Lucia",
    capital: "Castries",
    region: "Americas",
    population: 183629,
    flag: "https://flagcdn.com/lc.svg",
    independent: false,
  },
  {
    name: "Saint Martin (French part)",
    capital: "Marigot",
    region: "Americas",
    population: 38659,
    flag: "https://flagcdn.com/mf.svg",
    independent: false,
  },
  {
    name: "Saint Pierre and Miquelon",
    capital: "Saint-Pierre",
    region: "Americas",
    population: 6069,
    flag: "https://flagcdn.com/pm.svg",
    independent: false,
  },
  {
    name: "Saint Vincent and the Grenadines",
    capital: "Kingstown",
    region: "Americas",
    population: 110947,
    flag: "https://flagcdn.com/vc.svg",
    independent: false,
  },
  {
    name: "Samoa",
    capital: "Apia",
    region: "Oceania",
    population: 198410,
    flag: "https://flagcdn.com/ws.svg",
    independent: false,
  },
  {
    name: "San Marino",
    capital: "City of San Marino",
    region: "Europe",
    population: 33938,
    flag: "https://flagcdn.com/sm.svg",
    independent: false,
  },
  {
    name: "Sao Tome and Principe",
    capital: "São Tomé",
    region: "Africa",
    population: 219161,
    flag: "https://flagcdn.com/st.svg",
    independent: false,
  },
  {
    name: "Saudi Arabia",
    capital: "Riyadh",
    region: "Asia",
    population: 34813867,
    flag: "https://flagcdn.com/sa.svg",
    independent: false,
  },
  {
    name: "Senegal",
    capital: "Dakar",
    region: "Africa",
    population: 16743930,
    flag: "https://flagcdn.com/sn.svg",
    independent: false,
  },
  {
    name: "Serbia",
    capital: "Belgrade",
    region: "Europe",
    population: 6908224,
    flag: "https://flagcdn.com/rs.svg",
    independent: false,
  },
  {
    name: "Seychelles",
    capital: "Victoria",
    region: "Africa",
    population: 98462,
    flag: "https://flagcdn.com/sc.svg",
    independent: false,
  },
  {
    name: "Sierra Leone",
    capital: "Freetown",
    region: "Africa",
    population: 7976985,
    flag: "https://flagcdn.com/sl.svg",
    independent: false,
  },
  {
    name: "Singapore",
    capital: "Singapore",
    region: "Asia",
    population: 5685807,
    flag: "https://flagcdn.com/sg.svg",
    independent: false,
  },
  {
    name: "Sint Maarten (Dutch part)",
    capital: "Philipsburg",
    region: "Americas",
    population: 40812,
    flag: "https://flagcdn.com/sx.svg",
    independent: false,
  },
  {
    name: "Slovakia",
    capital: "Bratislava",
    region: "Europe",
    population: 5458827,
    flag: "https://flagcdn.com/sk.svg",
    independent: false,
  },
  {
    name: "Slovenia",
    capital: "Ljubljana",
    region: "Europe",
    population: 2100126,
    flag: "https://flagcdn.com/si.svg",
    independent: false,
  },
  {
    name: "Solomon Islands",
    capital: "Honiara",
    region: "Oceania",
    population: 686878,
    flag: "https://flagcdn.com/sb.svg",
    independent: false,
  },
  {
    name: "Somalia",
    capital: "Mogadishu",
    region: "Africa",
    population: 15893219,
    flag: "https://flagcdn.com/so.svg",
    independent: false,
  },
  {
    name: "South Africa",
    capital: "Pretoria",
    region: "Africa",
    population: 59308690,
    flag: "https://flagcdn.com/za.svg",
    independent: false,
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    capital: "King Edward Point",
    region: "Americas",
    population: 30,
    flag: "https://flagcdn.com/gs.svg",
    independent: false,
  },
  {
    name: "Korea (Republic of)",
    capital: "Seoul",
    region: "Asia",
    population: 51780579,
    flag: "https://flagcdn.com/kr.svg",
    independent: false,
  },
  {
    name: "Spain",
    capital: "Madrid",
    region: "Europe",
    population: 47351567,
    flag: "https://flagcdn.com/es.svg",
    independent: false,
  },
  {
    name: "Sri Lanka",
    capital: "Sri Jayawardenepura Kotte",
    region: "Asia",
    population: 21919000,
    flag: "https://flagcdn.com/lk.svg",
    independent: false,
  },
  {
    name: "Sudan",
    capital: "Khartoum",
    region: "Africa",
    population: 43849269,
    flag: "https://flagcdn.com/sd.svg",
    independent: false,
  },
  {
    name: "South Sudan",
    capital: "Juba",
    region: "Africa",
    population: 11193729,
    flag: "https://flagcdn.com/ss.svg",
    independent: false,
  },
  {
    name: "Suriname",
    capital: "Paramaribo",
    region: "Americas",
    population: 586634,
    flag: "https://flagcdn.com/sr.svg",
    independent: false,
  },
  {
    name: "Svalbard and Jan Mayen",
    capital: "Longyearbyen",
    region: "Europe",
    population: 2562,
    flag: "https://flagcdn.com/sj.svg",
    independent: false,
  },
  {
    name: "Swaziland",
    capital: "Mbabane",
    region: "Africa",
    population: 1160164,
    flag: "https://flagcdn.com/sz.svg",
    independent: false,
  },
  {
    name: "Sweden",
    capital: "Stockholm",
    region: "Europe",
    population: 10353442,
    flag: "https://flagcdn.com/se.svg",
    independent: false,
  },
  {
    name: "Switzerland",
    capital: "Bern",
    region: "Europe",
    population: 8636896,
    flag: "https://flagcdn.com/ch.svg",
    independent: false,
  },
  {
    name: "Syrian Arab Republic",
    capital: "Damascus",
    region: "Asia",
    population: 17500657,
    flag: "https://flagcdn.com/sy.svg",
    independent: false,
  },
  {
    name: "Taiwan",
    capital: "Taipei",
    region: "Asia",
    population: 23503349,
    flag: "https://flagcdn.com/tw.svg",
    independent: false,
  },
  {
    name: "Tajikistan",
    capital: "Dushanbe",
    region: "Asia",
    population: 9537642,
    flag: "https://flagcdn.com/tj.svg",
    independent: false,
  },
  {
    name: "Tanzania, United Republic of",
    capital: "Dodoma",
    region: "Africa",
    population: 59734213,
    flag: "https://flagcdn.com/tz.svg",
    independent: false,
  },
  {
    name: "Thailand",
    capital: "Bangkok",
    region: "Asia",
    population: 69799978,
    flag: "https://flagcdn.com/th.svg",
    independent: false,
  },
  {
    name: "Timor-Leste",
    capital: "Dili",
    region: "Asia",
    population: 1318442,
    flag: "https://flagcdn.com/tl.svg",
    independent: false,
  },
  {
    name: "Togo",
    capital: "Lomé",
    region: "Africa",
    population: 8278737,
    flag: "https://flagcdn.com/tg.svg",
    independent: false,
  },
  {
    name: "Tokelau",
    capital: "Fakaofo",
    region: "Oceania",
    population: 1411,
    flag: "https://flagcdn.com/tk.svg",
    independent: false,
  },
  {
    name: "Tonga",
    capital: "Nuku'alofa",
    region: "Oceania",
    population: 105697,
    flag: "https://flagcdn.com/to.svg",
    independent: false,
  },
  {
    name: "Trinidad and Tobago",
    capital: "Port of Spain",
    region: "Americas",
    population: 1399491,
    flag: "https://flagcdn.com/tt.svg",
    independent: false,
  },
  {
    name: "Tunisia",
    capital: "Tunis",
    region: "Africa",
    population: 11818618,
    flag: "https://flagcdn.com/tn.svg",
    independent: false,
  },
  {
    name: "Turkey",
    capital: "Ankara",
    region: "Asia",
    population: 84339067,
    flag: "https://flagcdn.com/tr.svg",
    independent: false,
  },
  {
    name: "Turkmenistan",
    capital: "Ashgabat",
    region: "Asia",
    population: 6031187,
    flag: "https://flagcdn.com/tm.svg",
    independent: false,
  },
  {
    name: "Turks and Caicos Islands",
    capital: "Cockburn Town",
    region: "Americas",
    population: 38718,
    flag: "https://flagcdn.com/tc.svg",
    independent: false,
  },
  {
    name: "Tuvalu",
    capital: "Funafuti",
    region: "Oceania",
    population: 11792,
    flag: "https://flagcdn.com/tv.svg",
    independent: false,
  },
  {
    name: "Uganda",
    capital: "Kampala",
    region: "Africa",
    population: 45741000,
    flag: "https://flagcdn.com/ug.svg",
    independent: false,
  },
  {
    name: "Ukraine",
    capital: "Kyiv",
    region: "Europe",
    population: 44134693,
    flag: "https://flagcdn.com/ua.svg",
    independent: false,
  },
  {
    name: "United Arab Emirates",
    capital: "Abu Dhabi",
    region: "Asia",
    population: 9890400,
    flag: "https://flagcdn.com/ae.svg",
    independent: false,
  },
  {
    name: "United Kingdom of Great Britain and Northern Ireland",
    capital: "London",
    region: "Europe",
    population: 67215293,
    flag: "https://flagcdn.com/gb.svg",
    independent: false,
  },
  {
    name: "United States of America",
    capital: "Washington, D.C.",
    region: "Americas",
    population: 329484123,
    flag: "https://flagcdn.com/us.svg",
    independent: false,
  },
  {
    name: "Uruguay",
    capital: "Montevideo",
    region: "Americas",
    population: 3473727,
    flag: "https://flagcdn.com/uy.svg",
    independent: false,
  },
  {
    name: "Uzbekistan",
    capital: "Tashkent",
    region: "Asia",
    population: 34232050,
    flag: "https://flagcdn.com/uz.svg",
    independent: false,
  },
  {
    name: "Vanuatu",
    capital: "Port Vila",
    region: "Oceania",
    population: 307150,
    flag: "https://flagcdn.com/vu.svg",
    independent: false,
  },
  {
    name: "Venezuela (Bolivarian Republic of)",
    capital: "Caracas",
    region: "Americas",
    population: 28435943,
    flag: "https://flagcdn.com/ve.svg",
    independent: false,
  },
  {
    name: "Vietnam",
    capital: "Hanoi",
    region: "Asia",
    population: 97338583,
    flag: "https://flagcdn.com/vn.svg",
    independent: false,
  },
  {
    name: "Wallis and Futuna",
    capital: "Mata-Utu",
    region: "Oceania",
    population: 11750,
    flag: "https://flagcdn.com/wf.svg",
    independent: false,
  },
  {
    name: "Western Sahara",
    capital: "El Aaiún",
    region: "Africa",
    population: 510713,
    flag: "https://flagcdn.com/eh.svg",
    independent: false,
  },
  {
    name: "Yemen",
    capital: "Sana'a",
    region: "Asia",
    population: 29825968,
    flag: "https://flagcdn.com/ye.svg",
    independent: false,
  },
  {
    name: "Zambia",
    capital: "Lusaka",
    region: "Africa",
    population: 18383956,
    flag: "https://flagcdn.com/zm.svg",
    independent: false,
  },
  {
    name: "Zimbabwe",
    capital: "Harare",
    region: "Africa",
    population: 14862927,
    flag: "https://flagcdn.com/zw.svg",
    independent: false,
  },
];

export default tempData;
